#!/bin/bash

/* program to output a system information page */

	title="System Information Report"


echo "<HTML>
     <HEAD>

     <TITLE>$title</TITLE>


     </HEAD>

     <BODY>
    
	<h1>$title</h1>
     </BODY>
 </HTML>"

