#!/bin/bash

/* program to output a system information page */

	TITLE="System Information Report for $HOSTNAME"
	CURRENT_TIME=$(date +"%x %r %z")
	TIME-STAMP="Generated $CURRENT_TIME, by $USER"

	cat << _EOF_

echo "<HTML>
     <HEAD>

     <TITLE>$TITLE</TITLE>


     </HEAD>

     <BODY>
    
	<h1>$TITLE</h1>
	<P> $TIME_STAMP</p>
     </BODY>
 </HTML>"
_EOF_
